trigger:
  branches:
    include:
    - master
  paths:
    include:
    - wikipedia/*

pr:
  autoCancel: false
  branches:
    include:
    - master
  paths:
    include:
    - wikipedia/*

jobs:
- job: Test
  timeoutInMinutes: 5
  pool:
    vmImage: 'ubuntu-16.04'
  container: hseeberger/scala-sbt:8u222_1.3.7_2.12.10
  steps:
  - bash: cd wikipedia && sbt test
    displayName: 'Run unit tests'
